"""finance-plots — plot helpers."""

from ._alpha import (
    plot_cumulative_factor_returns,
    plot_ic_by_group,
    plot_ic_heatmap,
    plot_ic_hist,
    plot_ic_qq,
    plot_ic_ts,
    plot_quantile_returns_bar,
    plot_rolling_ic,
    plot_top_bottom_quantile_turnover,
)
from ._indicators import plot_indicator_panel, plot_price_with_overlays
from ._portfolio import (
    plot_correlation_matrix,
    plot_cost_breakdown_bar,
    plot_covariance_eigenvalues,
    plot_efficient_frontier,
    plot_execution_timeline,
    plot_factor_exposure_heatmap,
    plot_market_impact_curve,
    plot_portfolio_weight_evolution,
    plot_return_attribution_stacked,
    plot_risk_decomposition_stacked,
    plot_weight_diff,
)
from ._post_trade import plot_execution_quality, plot_mfe_mae_scatter, plot_trading_cost_breakdown_bar
from ._returns import (
    plot_drawdown_underwater,
    plot_return_scatter,
    plot_returns,
    plot_returns_bar,
    plot_returns_dist,
    plot_returns_heatmap,
    plot_returns_timeseries,
    plot_rolling_beta,
    plot_rolling_correlation,
    plot_rolling_returns,
    plot_rolling_sharpe,
    plot_rolling_volatility,
)

__all__ = [
    "plot_returns",
    "plot_rolling_returns",
    "plot_rolling_volatility",
    "plot_rolling_sharpe",
    "plot_rolling_beta",
    "plot_rolling_correlation",
    "plot_return_scatter",
    "plot_drawdown_underwater",
    "plot_returns_heatmap",
    "plot_returns_bar",
    "plot_returns_dist",
    "plot_returns_timeseries",
    "plot_indicator_panel",
    "plot_price_with_overlays",
    "plot_trading_cost_breakdown_bar",
    "plot_mfe_mae_scatter",
    "plot_execution_quality",
    "plot_ic_ts",
    "plot_ic_hist",
    "plot_ic_qq",
    "plot_ic_by_group",
    "plot_ic_heatmap",
    "plot_rolling_ic",
    "plot_quantile_returns_bar",
    "plot_top_bottom_quantile_turnover",
    "plot_cumulative_factor_returns",
    "plot_efficient_frontier",
    "plot_market_impact_curve",
    "plot_execution_timeline",
    "plot_cost_breakdown_bar",
    "plot_return_attribution_stacked",
    "plot_portfolio_weight_evolution",
    "plot_weight_diff",
    "plot_risk_decomposition_stacked",
    "plot_factor_exposure_heatmap",
    "plot_correlation_matrix",
    "plot_covariance_eigenvalues",
]
