# Changes here will be overwritten by Copier
_commit: c124449
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: false
email: prettygoodcapital@gmail.com
github: prettygoodcapital
project_description: Standard financial plots
project_name: finance plots
python_version_primary: '3.11'
team: PrettyGoodCapital
