"""finance-plots — plotting and table helpers."""

from __future__ import annotations

__version__ = "0.1.0"

from .plots import (  # noqa: F401
    plot_cumulative_factor_returns,
    plot_drawdown_underwater,
    plot_execution_quality,
    plot_ic_by_group,
    plot_ic_heatmap,
    plot_ic_hist,
    plot_ic_qq,
    plot_ic_ts,
    plot_indicator_panel,
    plot_mfe_mae_scatter,
    plot_price_with_overlays,
    plot_quantile_returns_bar,
    plot_return_scatter,
    plot_returns,
    plot_returns_bar,
    plot_returns_dist,
    plot_returns_heatmap,
    plot_returns_timeseries,
    plot_rolling_beta,
    plot_rolling_correlation,
    plot_rolling_ic,
    plot_rolling_returns,
    plot_rolling_sharpe,
    plot_rolling_volatility,
    plot_top_bottom_quantile_turnover,
    plot_trading_cost_breakdown_bar,
)
from .tables import (  # noqa: F401
    perf_stats,
    table_cost_breakdown,
    table_drawdowns,
    table_execution_quality,
    table_information,
    table_perf_stats,
    table_period_returns,
    table_quantile_statistics,
    table_returns_by_quantile,
    table_round_trip_stats,
    table_turnover,
)

__all__ = [
    "plot_returns",
    "plot_rolling_returns",
    "plot_rolling_volatility",
    "plot_rolling_sharpe",
    "plot_rolling_beta",
    "plot_rolling_correlation",
    "plot_return_scatter",
    "plot_drawdown_underwater",
    "plot_returns_heatmap",
    "plot_returns_bar",
    "plot_returns_dist",
    "plot_returns_timeseries",
    "plot_indicator_panel",
    "plot_price_with_overlays",
    "plot_trading_cost_breakdown_bar",
    "plot_mfe_mae_scatter",
    "plot_execution_quality",
    "plot_ic_ts",
    "plot_ic_hist",
    "plot_ic_qq",
    "plot_ic_by_group",
    "plot_ic_heatmap",
    "plot_rolling_ic",
    "plot_quantile_returns_bar",
    "plot_top_bottom_quantile_turnover",
    "plot_cumulative_factor_returns",
    "perf_stats",
    "table_perf_stats",
    "table_period_returns",
    "table_drawdowns",
    "table_cost_breakdown",
    "table_round_trip_stats",
    "table_execution_quality",
    "table_information",
    "table_returns_by_quantile",
    "table_turnover",
    "table_quantile_statistics",
]
